version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./line-gpt-credential.json:/app/secrets/gcp-key.json:ro
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/gcp-key.json
